spring.application.name=service-marketplace

spring.mongodb.uri=${MONGO_URI}

security.jwt.secret-key=${SECRET_KEY}

security.jwt.expiration-time=${EXPIRATION_TIME}

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey

spring.mail.password=${SEND_GRID_API}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

custom.app.sender.email=${VERIFICATION_EMAIL}

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY}