package com.ServiceMarketplace.service_marketplace.model;

public enum NotificationType {
    NEW_MESSAGE,
    PRICE_OFFER_RECEIVED,
    PRICE_OFFER_ACCEPTED,
    PRICE_OFFER_REJECTED,
    BOOKING_REQUESTED,
    BOOKING_CONFIRMED,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    BOOKING_REJECTED,
    REVIEW_RECEIVED
}
