name: CI Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  frontend-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 
      - run: npm ci
      - run: npm install @rollup/rollup-linux-x64-gnu
      - run: npm run -w packages/frontend lint 
      - run: npm run -w packages/frontend build
  
  # These tests work locally, we need to create "test" env variables so they pass in github
  backend-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'packages/backend/service-marketplace/pom.xml' 
          
      - name: Run Backend Tests
        working-directory: packages/backend/service-marketplace
        env:
          MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
          SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
          EXPIRATION_TIME: 3600000
          SEND_GRID_API: ${{ secrets.TEST_SEND_GRID_API }}
          VERIFICATION_EMAIL: test@example.com
          STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.TEST_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.TEST_STRIPE_WEBHOOK_SECRET }}
          STRIPE_CONNECT_RETURN_URL: http://localhost:5173/profile
          STRIPE_CONNECT_REFRESH_URL: http://localhost:5173/profile
        run: mvn clean test
